// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1572816989);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1572817109);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1572816629);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1572816749);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1572816869);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1574);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1572816600);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{68abb633-77d7-4369-ab45-3387a410759b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1572816665847");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1572818453847");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1572816617616");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1572820217616");
user_pref("browser.search.region", "SV");
user_pref("browser.slowStartup.averageTime", 17741);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191022215001");
user_pref("browser.startup.homepage_override.mstone", "68.2.0");
user_pref("browser.startup.lastColdStartupCheck", 1572816608);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1572816615569");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.2.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 01 Nov 2019 13:00:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1572816990);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.2.0");
user_pref("extensions.lastPlatformVersion", "68.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9c19368d-3d32-42a3-b0b4-1f6ac92bc2e3\",\"fxmonitor@mozilla.org\":\"cb0c6f6b-c698-4f8f-a55d-9330ca8ecd57\",\"screenshots@mozilla.org\":\"24a36b06-3be5-458c-9104-8a6b2511705a\",\"webcompat-reporter@mozilla.org\":\"b24ed1b9-8947-4cf6-805c-84ff6667f3bf\",\"webcompat@mozilla.org\":\"f6dc1926-a4a4-4394-a642-f49a5cc0409b\",\"default-theme@mozilla.org\":\"ef091858-27a4-4b41-a747-4267fb73e2b9\",\"google@search.mozilla.org\":\"0bfa095e-38cf-40e6-9427-74f818d7b444\",\"bing@search.mozilla.org\":\"8c6eb2e4-412a-4874-916a-5e5f3acd19e5\",\"drae@search.mozilla.org\":\"6489cc94-a786-4252-9483-ca48a5120559\",\"ddg@search.mozilla.org\":\"a3d22c9f-531c-4874-9713-65230e7bb2ae\",\"ebay@search.mozilla.org\":\"74afcd56-bf7b-4e43-ac74-70864f96a098\",\"twitter@search.mozilla.org\":\"95549d21-f0a3-4643-b2de-60696129c402\",\"wikipedia@search.mozilla.org\":\"0bc9bce8-4c0b-4bfe-b178-f5aab7016562\"}");
user_pref("media.gmp-manager.buildID", "20191022215001");
user_pref("media.gmp-manager.lastCheck", 1572816696);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f9004953-5499-47b5-b936-2e98d0f5e74d");
user_pref("security.sandbox.plugin.tempDirSuffix", "4270d376-595a-4d26-8451-824a680f5a27");
user_pref("services.blocklist.pinning.checked", 1572816869);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1572653775258\"");
user_pref("services.settings.last_update_seconds", 1572816869);
user_pref("services.settings.main.cfr-fxa.last_check", 1572816869);
user_pref("services.settings.main.cfr.last_check", 1572816869);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1572816869);
user_pref("services.settings.main.hijack-blocklists.last_check", 1572816869);
user_pref("services.settings.main.language-dictionaries.last_check", 1572816869);
user_pref("services.settings.main.sites-classification.last_check", 1572816869);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1572816869);
user_pref("services.settings.security.onecrl.checked", 1572816869);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1572816590);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20191022215001");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
